# .github/workflows/html-validate.yml

name: HTML Validate

on:
  push:
    branches: [main, feature3]
  pull_request:
    branches: [main]

jobs:
  html-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # or '20' if you prefer

      - name: Install html-validate
        run: npm install -g html-validate

      - name: Run HTML validation
        run: html-validate .
